version: '3.9'
services:
    dikser:
        # dikenang server API Image
        build:
            dockerfile: Dockerfile
            context: ./dikser
        depends_on:
            - postgres
        ports:
            - '3000:3000'
        environment:
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USERNAME: postgres
            DB_PASSWORD: admin
            DB_NAME: dikenang-local
            # Another env variables are defined in .env file

    postgres:
        # postgres database image
        image: postgres:latest
        ports:
            - '35000:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: dikenang-local
