version: '3.9'
services:
    dikser:
        # dikenang server API Image
        build: ./dikser
        depends_on:
            - postgres
        ports:
            - '3000:3000'
        environment:
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USERNAME: postgres
            DB_PASSWORD: admin
            DB_NAME: dikenang-local
            JWT_SECRET: secret-example-of-jwt-token

    postgres:
        # postgres database image
        image: postgres:latest
        ports:
            - '35000:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: dikenang-local
