# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
    push:
        branches: [staging, production]
    pull_request:
        branches: [staging, production]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./dikser
        strategy:
            matrix:
                node-version: [14.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Deps
              run: yarn
            - name: Build
              run: yarn build
            - name: Testing
              run: yarn test
