
name: deploy dikser to heroku

on:
  push:
    branches:
      - production
    paths:
      - "dikser/**"
      - ".github/workflows/publish_heroku.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Add backend remote origin
        run: git remote add heroku-backend https://heroku:${{ secrets.HEROKU_AUTH_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      
      - name: Deploy dikser to Heroku
        run: git push heroku-backend `git subtree split --prefix dikser production`:refs/heads/master --force
